### ISSUE TITLE
text changes in data descriptions

### ISSUE THREAD

**Issue by avweigel** [janelia-cosem/dataset_descriptions#2]
### jrc_ctl-id8-1
- Change "Title" to:
   *Killer T-Cell attacking cancer cell*
- Change "Sample" to:
   *OT-I mouse cytotoxic T lymphocyte attacking an ID8 cell*

### jrc_fly-acc-calyx-1
- Change "Title" to:
   *Drosophila brain: Accessory calyx*

### jrc_fly-fsb-1
- Change "Title" to:
   *Drosophila brain: Fan-shaped body*

### jrc_hela-2
- Change "Title" to:
   *Interphase HeLa cell*
- Change "Sample" to:
   *Wild-type, interphase HeLa cell*

### jrc_hela-3
- Change "Title" to:
   *Interphase HeLa cell*
- Change "Sample" to:
   *Wild-type, interphase HeLa cell*

### jrc_hela-4
- Change "Title" to:
   *Mitotic HeLa cell*
- Change "Sample" to:
   *Wild-type HeLa cell undergoing mitosis*

### jrc_jurkat-1
- Change "Title" to:
   *Immortalized T-Cells (Jurkat)*
- Change "Sample" to:
   *Wild-type Jurkats*

### jrc_macrophage-2
- Change "Title" to:
   *Macrophage cell*
- Change "Sample" to:
   *Wild-type THP-1 macrophage*

### jrc_mus-pancreas-1
- Change "Title" to:
   *Isolated Murine Pancreatic Islets*

### jrc_sum-159-1
- Change "Title" to:
   *Immortalized breast cancer cell (SUM159)*
- Change "Sample" to:
   *Wild-type SUM-159 cell*

**Comment by d-v-b** [comment]
closed by https://github.com/janelia-cosem/dataset_descriptions/commit/cfa1753dfa9764d99cc6ea994ae824ae8b8b6991
